{% set version = "0.2.3" %}

package:
  name: pywin32-ctypes
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pywin32-ctypes/pywin32-ctypes-{{ version }}.tar.gz
  sha256: d162dc04946d704503b2edc4d55f3dba5c1d539ead017afa00142c38b9885755

build:
  number: 1
  skip: true  # [not win]
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - win32ctypes

about:
  home: https://github.com/enthought/pywin32-ctypes
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A limited subset of pywin32 re-implemented using ctypes (or cffi)
  description: |
    A reimplementation of pywin32 that is pure python. The default behaviour
    will try to use cffi (>= 1.3.0), if available, and fall back to using ctypes.
  doc_url: http://pywin32-ctypes.readthedocs.io/en/stable/
  dev_url: https://github.com/enthought/pywin32-ctypes

extra:
  recipe-maintainers:
    - ccordoba12
